document: modularity-testing
version: 1
name: baseruntime
modulemd-url: http://pkgs.fedoraproject.org/cgit/modules/base-runtime.git/plain/base-runtime.yaml
service:
    port:
packages:
    profiles:
        - baseimage
    rpms:
default_module: docker
module:
    docker:
        setup: docker inspect base-runtime-smoke || python ./setup.py
        start:
        labels:
            #Short-term solution as there is no bugzilla component yet
            com.redhat.component: "https://github.com/fedora-modularity/base-runtime"
            name: "base-runtime"
            version: "0"
            release: "1"
            architecture: "x86_64"
            usage: "docker run --rm -it base-runtime/base-runtime bash"
            summary: "Minimal application runtime environment other modules can build upon."
            url: "https://github.com/fedora-modularity/base-runtime"
        source: http://pkgs.fedoraproject.org/cgit/modules/base-runtime.git
        container: docker=base-runtime-smoke
    rpm:
        start:
        stop:
        status:
        repos:
            - https://kojipkgs.stg.fedoraproject.org/compose/branched/jkaluza/latest-Boltron-26/compose/base-runtime/x86_64/os/
test:
    processrunnig:
        - 'ls  / | grep bin'
